#ifndef _MESSAGE_DEFINE_H_
#define _MESSAGE_DEFINE_H_

#define LENGTH_IV 12
#define LENGTH_AUTHEN_TAG 16
#define LENGTH_OUTPUT 128
#define LENGTH_SIGN_HMAC 32
#define LENGTH_SIGN_RSA 512
#define LENGTH_TICKET 34

#define SUCCESS 0
#define ERROR_CODE_INVALID_BYTES 1
#define ERROR_CODE_INVALID_CONNECTION_NAME 2
#define ERROR_CODE_INVALID_TOKEN 3

#endif
