#ifndef _MESSAGE_DEFINE_H_
#define _MESSAGE_DEFINE_H_

#define LENGTH_IV 12
#define LENGTH_AUTHEN_TAG 16
#define LENGTH_SIGN_HMAC 32
#define LENGTH_SIGN_RSA 512
#define LENGTH_TICKET 34

#endif // _MESSAGE_DEFINE_H_
